CREATE DATABASE IF NOT EXISTS m223_demo;

USE m223_demo;

CREATE USER 'm223_demo'@'%' IDENTIFIED BY 'globi.1234';

GRANT ALL PRIVILEGES
    ON m223_demo.*
    TO 'm223_demo'@'%';

CREATE TABLE IF NOT EXISTS Status (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name ENUM('STATUS_OFFEN', 'STATUS_IN_BEARBEITUNG', 'STATUS_ABGESCHLOSSEN') NOT NULL
);

INSERT INTO Status (id, name) VALUES (1, 'STATUS_OFFEN');
INSERT INTO Status (id, name) VALUES (2, 'STATUS_IN_BEARBEITUNG');
INSERT INTO Status (id, name) VALUES (3, 'STATUS_ABGESCHLOSSEN');